[platformio]
default_envs = esp12e
# Memberitahu PlatformIO bahwa file utama ada di root (WifiXv1.5.ino)
src_dir = .

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

# Pengaturan tambahan untuk optimasi build
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -Wl,-Teagle.flash.4m1m.ld

# Jika kode butuh library khusus, tambahkan di bawah sini
lib_deps =
    # Contoh: me-no-dev/ESP Async WebServer @ ^1.2.3
